pipeline {
    agent { label 'Jenkins-Agent' }
    tools {
        jdk 'Java17'
        maven 'Maven3'
    }

    stages{
        stage("Cleanup Workspace"){
                steps {
                cleanWs()
                }
        }

        stage("Checkout from SCM"){
                steps {
                    git branch: 'main', credentialsId: 'github', url: 'https://github.com/dali05/kata'
                }
        }

        stage('Run Backend Jenkinsfile') {
                    steps {
                        dir('backend') {
                            load 'Jenkinsfile'
                        }
                    }
                }

        stage("Build Backend Application") {
                    steps {
                        dir('backend') {
                            sh "mvn clean package"
                        }
                    }
                }



        stage("Test Backend Application") {
                   steps {
                       dir('backend') {
                           sh "mvn test"
                       }
                   }
           }
}