apiVersion: v1
kind: Service
metadata:
  name: kata-backend-service
  labels:
    app: kata-backend
spec:
  selector:
    app: kata-backend

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
